from enum import StrEnum


class ReasonCode(StrEnum):
    PASSED = "PASSED"
    POLICY_MISSING = "POLICY_MISSING"
    DATA_NOT_KNOWN = "DATA_NOT_KNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    LIMIT_BREACH = "LIMIT_BREACH"
    MODE_NOT_PROMOTED = "MODE_NOT_PROMOTED"
